### ISSUE TITLE
"Type mismatch" when using in Java

### ISSUE THREAD

**Issue by smashinghamster** [andresteingress/gcontracts#52]
Hi.

Does GContracts support being used in Java?

I tried successfully to create a Maven Java project and import the GContracts library as a dependency, but the first "@Requires(_some boolean expression_)" gives me a compile-time error saying, 

"Type mismatch: cannot convert from boolean to Class".

Wolfgang

**Comment by paulk-asert** [comment]
I highly doubt it could be used with Java.

**Comment by smashinghamster** [comment]
Thank you -- in the meantime, I thought so anyway.
